# Generated by Django 4.1.1 on 2022-09-30 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_name', models.CharField(max_length=20)),
                ('bus_num', models.IntegerField()),
                ('start', models.CharField(max_length=30)),
                ('end', models.CharField(max_length=30)),
                ('seats', models.IntegerField()),
                ('balanseat', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='consumer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('address', models.TextField()),
                ('phone', models.PositiveBigIntegerField()),
                ('start', models.CharField(max_length=30)),
                ('end', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
    ]
