# Generated by Django 4.1.1 on 2022-10-13 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlinebus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bus_num',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_no', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='driver',
            name='bus_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlinebus.bus_num'),
        ),
    ]
